project:
  name : vhr

server:
  port : 8081

spring:
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource
    url : jdbc:mysql://localhost:3306/vhr?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    #    &useSSL=false&allowPublicKeyRetrieval=true
    username : root
    password : 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml

